language: go

go:
- "1.12.x"

env:
  global:
  - GO111MODULE=on

install:
- go mod download

script:
- go test ./exitcode/...
- go test ./file/...
- go test ./prompt/...
- go test ./rwi/...
- go test ./signal/...
